import { Link } from 'wouter'
import { ArrowRight, Backpack, CalendarDays, Camera, Compass, Heart, MapPin, Mountain, ShieldCheck, Sparkles, Users, Waves } from 'lucide-react'
import { PageFrame } from '@/components/site-shell'
import { destinations } from '@/lib/destinations'

const images = ['/images/adventure-hero.png','/images/adventure-mountain.png','/images/adventure-camp.png','/images/adventure-mountain.png','/images/adventure-coast.png','/images/adventure-coast.png','/images/adventure-mountain.png','/images/adventure-camp.png']
const details = ['Big 5 • Game Drives • Luxury Stays','Elephants • Kilimanjaro Views • Culture','Unique Wildlife • River Activities • Culture','Boat Rides • Hell\'s Gate • Hot Springs','Beaches • Water Sports • Nightlife','Snorkelling • Marine Life • Relaxation','Mount Kenya • Hiking • Nature','Sandy Beaches • Marine Life • Culture']
const categories = [['Safari & Wildlife', Camera],['Beach & Coastline', Waves],['Camping & Outdoors', Mountain],['Road Trips & Excursions', Compass],['Group Experiences', Users]] as const
const packages = [['Maasai Mara Villa Escape','/images/adventure-camp.png','3 Days / 2 Nights','From KES 12,800 pp'],['Mombasa Beach Escape','/images/adventure-coast.png','3 Days / 2 Nights','KES 12,800 pp'],['Naivasha Adventure','/images/adventure-mountain.png','1 Day','From KES 5,500 pp'],['Samburu Overland','/images/adventure-hero.png','2 Days / 1 Night','From KES 16,000 pp'],['Wild Hearts Escape','/images/adventure-camp.png','2 Days / 1 Night','From KES 24,400 pp/couple'],['Girls\' Adventure Escape','/images/group-travel-hero.png','3 Days / 2 Nights','From KES 12,400 pp']]
const essentials = [['Visa information', ShieldCheck],['Travel insurance', ShieldCheck],['Packing tips', Backpack],['Health & safety', Heart],['Payment options', MapPin]] as const

export default function DestinationsPage() {
  return <PageFrame><main className="destinations-catalogue">
    <section className="destinations-hero" style={{backgroundImage:"linear-gradient(90deg,rgba(0,35,29,.82),rgba(0,35,29,.15)),url('/images/adventure-hero.png')"}}><div><span className="orange-kicker">Explore Kenya</span><h1>Iconic destinations.<br/><em>Unforgettable experiences.</em></h1><p>From the savannahs to the coastline, Kenya is a beautiful blend of wildlife, culture, adventure and natural wonders.</p><div className="destinations-hero-features"><span><Mountain/>Stunning landscapes</span><span><Sparkles/>Amazing wildlife</span><span><Compass/>Rich culture</span><span><CalendarDays/>Year-round adventures</span></div></div></section>
    <section className="our-destinations"><header className="catalogue-heading"><div><span className="orange-kicker">Our destinations</span><h2>Discover Kenya&apos;s best places</h2><p>Each destination has its unique story, and we&apos;re here to help you experience it.</p></div><nav className="destination-categories">{categories.map(([label,Icon])=><span key={label}><Icon/>{label}</span>)}</nav></header><div className="destination-showcase-grid">{destinations.slice(0,8).map((destination,index)=><Link key={destination.slug} href={`/destinations/${destination.slug}`} className="destination-showcase-card" style={{backgroundImage:`linear-gradient(0deg,rgba(0,40,34,.9),transparent 74%),url('${images[index]}')`}}><div><h3>{destination.name}</h3><p>{details[index]}</p><span>Explore <ArrowRight/></span></div></Link>)}</div></section>
    <section className="featured-packages"><header className="catalogue-heading"><div><span className="orange-kicker">Featured packages</span><h2>Handpicked experiences</h2></div><Link href="/adventures">View all destinations <ArrowRight/></Link></header><div className="package-grid">{packages.map(([name,image,days,price])=><article key={name}><img src={image} alt={name}/><div><h3>{name}</h3><small><CalendarDays/>{days}</small><strong>{price}</strong><Link href="/plan">View package <ArrowRight/></Link></div></article>)}</div></section>
    <section className="destination-bottom"><article className="travel-essentials"><span className="orange-kicker">Travel essentials</span><h2>Plan with confidence.</h2><p>Here&apos;s what you need to know before you go, so you can travel stress-free.</p><div>{essentials.map(([label,Icon])=><span key={label}><Icon/>{label}</span>)}</div><Link href="/contact" className="button">View travel guide <ArrowRight/></Link></article><article className="custom-destination-trip"><span className="orange-kicker">Custom trips</span><h2>Can&apos;t find exactly what you want?</h2><p>Tell us where you want to go, who you&apos;re travelling with, and your budget. We&apos;ll build the experience around you.</p><Link href="/plan" className="button">Plan my adventure <ArrowRight/></Link></article></section>
    <section className="destination-contact"><div><h2>So... where are we going?</h2><p>Your next story is waiting.</p></div><a href="https://wa.me/254726843677">WhatsApp 0726 843 677</a><Link href="/plan" className="button">Plan my adventure <ArrowRight/></Link></section>
  </main></PageFrame>
}
