'use client'

import { BarChart3, CalendarCheck, FileText, LayoutDashboard, LogOut, Map, Menu, Settings, Users, X } from 'lucide-react'
import { useState } from 'react'

const stats = [['Total bookings', '128', '+18.2%', CalendarCheck], ['Customers', '2,486', '+12.4%', Users], ['Revenue', 'KES 842,500', '+24.8%', BarChart3], ['Published trips', '24', '+4 new', Map]] as const
const bookings = [['BK-1048', 'Sarah Wanjiku', 'Maasai Mara Villa Escape', '12 Sep 2026', 'Confirmed'], ['BK-1047', 'Brian Kamau', 'Mombasa Beach Escape', '28 Sep 2026', 'Pending'], ['BK-1046', 'Aisha Njeri', 'Naivasha Adventure', '04 Oct 2026', 'Confirmed'], ['BK-1045', 'James Otieno', 'Samburu Overland', '18 Oct 2026', 'New']] as const

export default function AdminPage() {
  const [open, setOpen] = useState(false)
  return <div className="admin-shell"><aside className={open ? 'admin-sidebar open' : 'admin-sidebar'}><div className="admin-logo"><span>Linkups</span><small>ADVENTURES</small></div><button className="admin-close" onClick={() => setOpen(false)}><X /></button><nav>{[['Overview', LayoutDashboard], ['Bookings', CalendarCheck], ['Adventures', Map], ['Destinations', Map], ['Customers', Users], ['Blog posts', FileText]].map(([name, Icon], index) => <a className={index === 0 ? 'active' : ''} href="#" key={name as string}><Icon />{name as string}</a>)}</nav><div className="admin-bottom"><a href="#"><Settings />Settings</a><a href="#"><LogOut />Sign out</a></div></aside><main className="admin-content"><header className="admin-header"><button className="admin-menu" onClick={() => setOpen(true)}><Menu /></button><div><p>Wednesday, 7 October 2026</p><h1>Good morning, Admin</h1></div><div className="admin-user"><span>LW</span><div><b>Linkups Admin</b><small>Administrator</small></div></div></header><section className="admin-page"><div className="admin-title"><div><span className="admin-eyebrow">Live overview</span><h2>Dashboard</h2></div><button className="admin-primary">+ Add adventure</button></div><div className="stat-grid">{stats.map(([name, value, change, Icon]) => <article className="stat-card" key={name}><div className="stat-icon"><Icon /></div><p>{name}</p><strong>{value}</strong><small>{change} this month</small></article>)}</div><div className="admin-grid"><section className="panel bookings-panel"><div className="panel-head"><div><h3>Recent bookings</h3><p>Manage and track your latest enquiries</p></div><a href="#">View all</a></div><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Adventure</th><th>Travel date</th><th>Status</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking[0]}>{booking.map((cell, i) => <td key={cell}>{i === 4 ? <span className={`status ${cell.toLowerCase()}`}>{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div></section><section className="panel activity-panel"><div className="panel-head"><div><h3>Quick actions</h3><p>Keep your site up to date</p></div></div><div className="quick-actions"><a href="#"><Map />Manage destinations</a><a href="#"><CalendarCheck />Review bookings</a><a href="#"><FileText />Write a blog post</a><a href="#"><Users />View customers</a></div></section></div></section></main></div>
}
