'use client'

import { useState } from 'react'
import { BarChart3, CalendarCheck, FileText, Image, LayoutDashboard, LogOut, Map, Menu, Settings, SlidersHorizontal, Users, X } from 'lucide-react'

const nav = [['Overview', LayoutDashboard], ['Bookings', CalendarCheck], ['Tours', Map], ['Destinations', Map], ['Users', Users], ['Media & banners', Image], ['Content', FileText], ['Settings', Settings]] as const
const tours = [['Maasai Mara Villa Escape','Maasai Mara','KES 24,800','Published'],['Mombasa Beach Escape','Mombasa','KES 12,800','Published'],['Naivasha Adventure','Naivasha','KES 5,500','Draft']] as const

export default function AdminPage(){
 const [open,setOpen]=useState(false); const [active,setActive]=useState('Overview'); const [saved,setSaved]=useState(false)
 return <div className="admin-shell"><aside className={open?'admin-sidebar open':'admin-sidebar'}><div className="admin-logo"><span>Linkups</span><small>ADVENTURES ADMIN</small></div><button className="admin-close" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button><nav>{nav.map(([name,Icon])=><button className={active===name?'active':''} key={name} onClick={()=>{setActive(name);setOpen(false)}}><Icon/>{name}</button>)}</nav><div className="admin-bottom"><button><SlidersHorizontal/>System health</button><button><LogOut/>Sign out</button></div></aside><main className="admin-content"><header className="admin-header"><button className="admin-menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button><div><p>Wednesday, 7 October 2026</p><h1>Good morning, Admin</h1></div><div className="admin-user"><span>LW</span><div><b>Linkups Admin</b><small>Administrator</small></div></div></header><section className="admin-page"><div className="admin-title"><div><span className="admin-eyebrow">Control centre</span><h2>{active}</h2></div><button className="admin-primary" onClick={()=>setSaved(true)}>Save changes</button></div>{saved&&<div className="success-box">Changes saved successfully. Connect your MySQL API to persist them live.</div>}{active==='Overview'&&<Overview/>}{active==='Tours'&&<Tours/>}{active==='Destinations'&&<Content title="Destinations" fields={['Name','Region','Short description','Hero image URL','Featured order']}/ >}{active==='Media & banners'&&<Content title="Banner slider" fields={['Slide title','Subtitle','Image URL','Button label','Button link']}/ >}{active==='Settings'&&<SettingsPanel/>}{active==='Bookings'&&<Bookings/>}{active==='Users'&&<UsersPanel/>}{active==='Content'&&<Content title="Site content" fields={['Page title','SEO description','Body content','Published status']}/ >}</section></main></div>
}
function Overview(){return <><div className="stat-grid">{[['Bookings','128','+18.2%'],['Customers','2,486','+12.4%'],['Revenue','KES 842,500','+24.8%'],['Published tours','24','+4 new']].map(([n,v,c])=><article className="stat-card" key={n}><p>{n}</p><strong>{v}</strong><small>{c} this month</small></article>)}</div><div className="admin-grid"><section className="panel"><div className="panel-head"><div><h3>Quick actions</h3><p>Manage the parts of your travel business that change most.</p></div></div><div className="admin-actions"><button className="admin-primary">+ New tour</button><button className="admin-secondary">Add destination</button><button className="admin-secondary">Upload banner</button><button className="admin-secondary">Review enquiries</button></div></section><section className="panel"><div className="panel-head"><div><h3>Live checklist</h3><p>Keep your storefront ready to convert.</p></div></div><div className="checklist"><p>✓ 24 tours published</p><p>✓ Banner slider configured</p><p>✓ Booking notifications enabled</p><p>! Connect production database</p></div></section></div></>}
function Tours(){return <div className="admin-section"><div className="admin-toolbar"><div><h3>Tour catalogue</h3><p>Create, edit, publish, price and schedule every adventure.</p></div><button className="admin-primary">+ Create tour</button></div><div className="admin-table-card"><table className="admin-table"><thead><tr><th>Tour</th><th>Destination</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{tours.map(t=><tr key={t[0]}><td><b>{t[0]}</b></td><td>{t[1]}</td><td>{t[2]}</td><td><span className="status confirmed">{t[3]}</span></td><td><button className="admin-secondary">Edit</button></td></tr>)}</tbody></table></div><div className="admin-form-grid"><Field label="Tour name"/><Field label="Slug"/><Field label="Price per person"/><Field label="Duration"/><Field label="Hero image URL" full/><Field label="Short description" full area/><Field label="Itinerary, inclusions and exclusions" full area/></div></div>}
function Content({title,fields}:{title:string,fields:string[]}){return <div className="admin-section"><div className="admin-toolbar"><div><h3>{title}</h3><p>Update content and preview changes before publishing.</p></div><div className="admin-actions"><button className="admin-secondary">Preview</button><button className="admin-primary">Publish</button></div></div><div className="admin-form-grid">{fields.map((f,i)=><Field key={f} label={f} full={i>2} area={i>1}/>)}</div></div>}
function Field({label,full,area}:{label:string;full?:boolean;area?:boolean}){return <label className={'admin-field'+(full?' full':'')}>{label}<small>Visible on the live website</small>{area?<textarea className="admin-textarea" placeholder={'Enter '+label.toLowerCase()}/>:<input className="admin-input" placeholder={'Enter '+label.toLowerCase()}/>}</label>}
function SettingsPanel(){return <div className="admin-settings-grid">{[['Email settings','Configure booking confirmations, enquiry alerts and sender identity.'],['Social login','Enable Google, Facebook or Apple sign-in for travellers.'],['Brand & SEO','Update logo, colors, metadata and social profiles.'],['Booking rules','Set deposits, capacity, cancellation and payment instructions.'],['Security','Manage admin roles, sessions, password policy and audit logs.'],['Notifications','Control email, WhatsApp and dashboard alerts.']].map(([title,desc])=><article className="admin-setting-card" key={title}><h4>{title}</h4><p>{desc}</p><div className="toggle"><span>Enabled</span><input type="checkbox" defaultChecked/></div></article>)}</div>}
function Bookings(){return <div className="admin-table-card"><table className="admin-table"><thead><tr><th>Reference</th><th>Customer</th><th>Adventure</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{[['BK-1048','Sarah Wanjiku','Maasai Mara Villa Escape','12 Sep 2026','Confirmed'],['BK-1047','Brian Kamau','Mombasa Beach Escape','28 Sep 2026','Pending'],['BK-1046','Aisha Njeri','Naivasha Adventure','04 Oct 2026','Confirmed']].map(row=><tr key={row[0]}>{row.map((v,i)=><td key={v}>{i===4?<span className="status confirmed">{v}</span>:v}</td>)}<td><button className="admin-secondary">Open</button></td></tr>)}</tbody></table></div>}
function UsersPanel(){return <div className="admin-table-card"><table className="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Joined</th><th>Action</th></tr></thead><tbody>{[['Aisha Njeri','aisha@example.com','Customer','06 Oct 2026'],['Brian Kamau','brian@example.com','Customer','28 Sep 2026'],['Admin User','admin@linkups.co.ke','Administrator','01 Jan 2026']].map(row=><tr key={row[1]}>{row.map(v=><td key={v}>{v}</td>)}<td><button className="admin-secondary">Manage</button></td></tr>)}</tbody></table></div>}
