import { Link } from 'wouter'
import { ArrowRight, CalendarDays, MapPin, Search, Sparkles, Users, Waves, Heart, TentTree, Mountain, Compass, Camera, ShieldCheck } from 'lucide-react'
import { PageFrame } from '@/components/site-shell'
import { AdventureCards } from '@/components/adventure-cards'

const categories = [
  ['Safari', '/images/adventure-hero.png', 'Wildlife escapes'], ['Beach Escapes', '/images/adventure-coast.png', 'Sun, sand & sea'], ['Camping & Outdoors', '/images/adventure-camp.png', 'Sleep under stars'], ['Road Trips', '/images/adventure-hero.png', 'Open-road stories'], ['Day Adventures', '/images/adventure-mountain.png', 'Make a day of it'], ['Couples & Romance', '/images/adventure-coast.png', 'Memories together'], ['Girls Trips', '/images/adventure-hero.png', 'Your people, your pace'], ['Family Adventures', '/images/adventure-camp.png', 'Joy for everyone'],
]
const vibes = [['Thrill Seeker', Mountain, 'Rafting · hiking · game drives'], ['Beach Baby', Waves, 'Sun · sand · swimming'], ['Wild & Free', TentTree, 'Camping · bonfires · nature'], ['Good Times Only', Users, 'Friends · music · games'], ['Wild Heart', Heart, 'Couples · romance · escapes'], ['Family Time', Users, 'Nature · wildlife · relaxation']] as const
export default function AdventuresPage() {
  return <PageFrame><main className="adventures-page">
    <section className="adventure-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(0,38,32,.84),rgba(0,38,32,.18)),url('/images/adventure-hero.png')` }}><div><span className="orange-kicker">Explore Kenya</span><h1>Find your next<br /><em>adventure.</em></h1><p>From wild safaris and epic road trips to beach escapes, camping nights and unforgettable group experiences.</p></div></section>
    <section className="adventure-search"><label><MapPin />Destination<select><option>Where do you want to go?</option><option>Maasai Mara</option><option>Mombasa</option><option>Naivasha</option></select></label><label><Compass />Trip type<select><option>Any trip type</option><option>Safari</option><option>Beach escape</option></select></label><label><CalendarDays />Duration<select><option>Any duration</option><option>1 day</option><option>2–4 days</option></select></label><label><Sparkles />Budget<select><option>Any budget</option><option>Under KES 15,000</option><option>Premium</option></select></label><button className="button orange">Explore <ArrowRight /></button></section>
    <section className="adventure-categories"><div className="category-row">{categories.map(([name,image,detail]) => <Link href="/adventures" className="category-tile" key={name}><img src={image} alt="" /><span>{name}</span><small>{detail}</small></Link>)}</div></section>
    <section className="adventure-section"><div className="section-heading"><div><span className="orange-kicker">Featured</span><h2>Adventures</h2><p>Handpicked experiences. Unforgettable memories.</p></div><Link href="/plan">Plan a custom trip <ArrowRight /></Link></div><AdventureCards variant="adventure" limit={6}/></section>
    <section className="vibe-section" style={{ backgroundImage: `linear-gradient(90deg,rgba(255,253,248,.94),rgba(255,253,248,.45)),url('/images/adventure-mountain.png')` }}><div className="section-heading"><div><span className="orange-kicker">Choose your</span><h2>Adventure vibe</h2><p>Tell us how you want to feel. We&apos;ll help you find where to go.</p></div></div><div className="vibe-grid">{vibes.map(([name, Icon, detail]) => <Link href="/plan" className="vibe-card" key={name}><Icon /><strong>{name}</strong><small>{detail}</small></Link>)}</div><Link className="button dark-button" href="/plan">Find my adventure <ArrowRight /></Link></section>
    <section className="adventure-section upcoming-section"><div className="section-heading"><div><span className="orange-kicker">Travel dates</span><h2>Need a specific departure?</h2><p>Send us your preferred dates and we’ll confirm availability.</p></div><Link href="/plan">Ask about dates <ArrowRight /></Link></div></section>
    <section className="why-section"><span className="orange-kicker">Why LinkUps?</span><h2>More than just trips.</h2><p>We create experiences.</p><div className="why-grid">{([['Curated experiences', Sparkles], ['Seamless coordination', ShieldCheck], ['Group specialists', Users], ['Flexible packages', Compass], ['Adventure first', Heart]] as const).map(([name,Icon]) => <div key={name}><Icon /><strong>{name}</strong><small>Thoughtful details, memorable moments.</small></div>)}</div></section>
  </main></PageFrame>
}
